logger:
  type: console
  opts:
    level: info
    name: test/all2all

datasources:
  - id: datasource.file.json
    type: FileDatasource
    opts:
      connection:
        uri: !REALPATH mocks/files/records.json
      fields:
        id: "id"
        createdAt: "createdAt"
        updatedAt: "updatedAt"
      execOpts:
        limit: 100
  - id: datasource.mongodb
    type: MongoDBDatasource
    opts:
      connection:
        uri: !ENV [XTRANSPORTER_MONGODB_URI, "mongodb://127.0.0.1:27017"]
        database: !ENV [XTRANSPORTER_MONGODB_DATABASE, "test"]
        collection: !ENV [XTRANSPORTER_MONGODB_DATABASE, "datasource"]
        clientOpts:
          useUnifiedTopology: true
      fields:
        id: "id"
        createdAt: "createdAt"
        updatedAt: "updatedAt"
  - id: datasource.es
    type: ESDatasource
    opts:
      connection:
        uri: !ENV [XTRANSPORTER_ES_URI, "http://127.0.0.1:9200"]
        database: !ENV [XTRANSPORTER_ES_DATABASE, "datasource_*"]
      fields:
        id: "id"
        createdAt: "createdAt"
        updatedAt: "updatedAt"

storages:
  - id: storage.file.json
    type: FileStorage
    opts:
      connection:
        uri: !REALPATH temp/files/records.json
      fields:
        id: "id"
        createdAt: "createdAt"
        updatedAt: "updatedAt"
  - id: storage.mongodb
    type: MongoDBStorage
    opts:
      connection:
        uri: !ENV [XTRANSPORTER_MONGODB_URI, "mongodb://127.0.0.1:27017"]
        database: !ENV [XTRANSPORTER_MONGODB_DATABASE, "test"]
        collection: !ENV [XTRANSPORTER_MONGODB_DATABASE, "storage"]
        clientOpts:
          useUnifiedTopology: true
      fields:
        id: "id"
        createdAt: "createdAt"
        updatedAt: "updatedAt"
  - id: storage.es
    type: ESStorage
    opts:
      connection:
        uri: !ENV [XTRANSPORTER_ES_URI, "http://127.0.0.1:9200"]
        database: !ENV [XTRANSPORTER_ES_DATABASE, "storage"]
        collection: !ENV [XTRANSPORTER_ES_COLLECTION, "publishedAt,YYYYMMDD"]
      fields:
        id: "id"
        createdAt: "createdAt"
        updatedAt: "updatedAt"
      execOpts:
        refresh: "true"

pipelines:
  - id: parser.builtin
    type: ParserPipeline
    opts:
      schema: !LOADER [mocks/schemas/parser.json]
  - id: filter.builtin
    type: FilterPipeline
    opts:
      schema: !LOADER [mocks/schemas/filter.json]
