logger:
  type: console
  opts:
    level: info
    name: test/file2file

datasources:
  - id: datasource.file.json
    type: FileDatasource
    opts:
      connection:
        uri: !REALPATH mocks/files/records.json
      fields:
        id: "id"
        createdAt: "createdAt"
        updatedAt: "updatedAt"

storages:
  - id: storage.file.json
    type: FileStorage
    opts:
      connection:
        uri: !REALPATH temp/files/records.json
      fields:
        id: "id"
        createdAt: "createdAt"
        updatedAt: "updatedAt"
  - id: mongodb
    type: MongoDBStorage
    opts:
      connection:
        uri: !ENV [XTRANSPORTER_MONGODB_URI, "mongodb://127.0.0.1:27017"]
        database: !ENV [XTRANSPORTER_MONGODB_DATABASE, "test"]
        collection: !ENV [XTRANSPORTER_MONGODB_DATABASE, "storage"]
        clientOpts:
          useUnifiedTopology: true
      fields:
        id: "id"
        createdAt: "createdAt"
        updatedAt: "updatedAt"

pipelines:
  - id: parser.builtin
    type: ParserPipeline
    opts:
      schema: !LOADER [mocks/schemas/parser.json]
  - id: filter.builtin
    type: FilterPipeline
    opts:
      schema: !LOADER [mocks/schemas/filter.json]
